#网站设置 | site setting
theme: jekyll-theme-merlot
title: oldli031
email: 397127598@qq.com
description: "oldli031的博客"
keyword: "oldli031的博客"
url: "http://oldli031.github.io"
github_repo: "https://github.com/oldli031/oldli031.github.io.git"
# Gitalk
<!-- Gitalk 评论 start  -->
{% if site.gitalk.enable %}
<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script>

<div id="gitalk-container"></div>
    <script type="text/javascript">
    var gitalk = new Gitalk({

    // gitalk的主要参数
        clientID: `6cd53528a877ac784170`,
        clientSecret: `9bacfd1dd361d9bf7980ae2594d47c157d6fcc5d`,
        repo: `https://oldli031.github.io/`,
        owner: 'oldli031',
        admin: ['oldli031'],
        id: 'window.location.pathname',

    });
    gitalk.render('gitalk-container');
</script>
{% endif %}
<!-- Gitalk end -->
